"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import PriceChart from "../components/PriceChart";
import ResearchAuditCard from "../components/ResearchAuditCard";
import { getPublicReport } from "../services/api";
import type { AgentReport } from "../types";

export default function PublicReport({ slug }: { slug: string }) {
  const [report, setReport] = useState<AgentReport | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    getPublicReport(slug)
      .then((r) => setReport(r.report))
      .catch((e: unknown) => setError(e instanceof Error ? e.message : "This shared report is unavailable."));
  }, [slug]);

  if (error) {
    return (
      <section className="card danger-card" style={{ marginTop: "1rem" }}>
        <p>{error}</p>
        <Link className="button button-secondary" href="/">Go to FINDEC →</Link>
      </section>
    );
  }
  if (!report) {
    return <section className="card" style={{ marginTop: "1rem" }}><p>Loading shared report…</p></section>;
  }

  return (
    <section className="grid page-shell report-printable">
      <div className="report-actions no-print">
        <span className="eyebrow">Public shared report — read only</span>
        <button className="button button-secondary" onClick={() => window.print()}>⤓ Export PDF</button>
      </div>
      <article className="hero-panel">
        <div>
          <p className="eyebrow">Shared Report</p>
          <h1 className="hero-title">{report.ticker} decision record</h1>
          <p className="hero-copy">{report.query}</p>
        </div>
        <div className="hero-strip">
          <div className="metric-card"><span className="metric-label">Action</span><strong>{report.recommendation.action.toUpperCase()}</strong></div>
          <div className="metric-card"><span className="metric-label">Risk profile</span><strong>{report.risk_profile}</strong></div>
          <div className="metric-card"><span className="metric-label">Score</span><strong>{report.score.toFixed(2)}</strong></div>
          <div className="metric-card"><span className="metric-label">Created</span><strong>{new Date(report.createdAt).toLocaleDateString()}</strong></div>
        </div>
      </article>

      <div className="report-board">
        <div className="report-main-column">
          <article className="card recommendation-panel">
            <div className="section-heading">
              <div><p className="eyebrow">Recommendation</p><h3>Final decision</h3></div>
            </div>
            <p className="recommendation-copy">{report.recommendation.reason}</p>
            <p className="recommendation-disclaimer">{report.disclaimer}</p>
          </article>
        </div>
        <aside className="report-analyst-column-compact">
          {report.prediction && (
            <article className="card analyst-workspace-compact">
              <div className="section-heading"><div><p className="eyebrow">Analyst Workspace</p><h3>Forecast</h3></div></div>
              <PriceChart prediction={report.prediction} />
            </article>
          )}
          {report.sentiment && <ResearchAuditCard sentiment={report.sentiment} />}
        </aside>
      </div>

      <p className="report-public-footer no-print">
        Generated by <Link href="/">FINDEC</Link> · decision support only, not financial advice.
      </p>
    </section>
  );
}
